[project]
name = "fastapi-uv"
version = "0.1.0"
description = "FastAPI with UV"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "tensorflow>=2.20.0",
    "uvicorn>=0.35.0",
]
