[project]
name = "chat-bot-mcp-version"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.67.0",
    "arxiv>=2.2.0",
    "mcp>=1.14.0",
    "nest-asyncio>=1.6.0",
]
